run:
  timeout: 5m
  go: "1.25.7"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt
    - gosimple
    - ineffassign
    - unused
    - bodyclose
    - contextcheck
    - noctx
    - gosec
    - gocognit
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocognit:
    min-complexity: 21

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - errcheck
        - gosec